import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { QueryProvider } from "./providers";
import { Toaster } from "@/components/ui/toaster";
import StoreProvider from "@/state/redux";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "GuyExchange",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <StoreProvider>
          <QueryProvider>
            {children}
            <Toaster />
          </QueryProvider>
      </StoreProvider>
      </body>
    </html>
  );
}
